import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, CalendarClock, Mail, NotebookPen, Sparkle } from "lucide-react";
import { ResponsibleAiNotice } from "@/components/AiOutput";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "AI Workplace Productivity Assistant" },
      {
        name: "description",
        content:
          "Automate workplace tasks with AI: generate professional emails, summarize meeting notes into action items and build prioritised schedules.",
      },
      { property: "og:title", content: "AI Workplace Productivity Assistant" },
      {
        property: "og:description",
        content: "Emails, meeting summaries and task plans — generated by AI in seconds.",
      },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: Dashboard,
});

const TOOLS = [
  {
    to: "/email",
    icon: Mail,
    title: "Smart Email Generator",
    desc: "Turn a one-line brief into a polished email — formal, friendly, persuasive and more.",
  },
  {
    to: "/meeting-notes",
    icon: NotebookPen,
    title: "Meeting Notes Summarizer",
    desc: "Condense long notes into a summary with decisions, owners, action items and deadlines.",
  },
  {
    to: "/planner",
    icon: CalendarClock,
    title: "AI Task Planner",
    desc: "Prioritise your workload and get a realistic, time-blocked daily or weekly schedule.",
  },
] as const;

function Dashboard() {
  return (
    <>
      <section className="rounded-3xl border border-border bg-card p-6 sm:p-10">
        <p className="label-mono text-accent">AI workspace</p>
        <h1 className="mt-4 max-w-2xl text-3xl uppercase leading-[0.95] sm:text-5xl">
          Automate the busywork of your workday
        </h1>
        <p className="mt-4 max-w-xl text-sm text-muted-foreground sm:text-base">
          Three AI assistants for the tasks that eat your time: writing emails, digesting meeting
          notes and planning your week.
        </p>
        <div className="mt-6 flex flex-wrap gap-3">
          <Link
            to="/email"
            className="inline-flex items-center rounded-full bg-primary px-5 py-2.5 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
          >
            Start with an email <ArrowRight className="ml-2 h-4 w-4" />
          </Link>
          <Link
            to="/planner"
            className="inline-flex items-center rounded-full border border-border px-5 py-2.5 text-sm font-medium transition-colors hover:bg-secondary"
          >
            Plan my day
          </Link>
        </div>
      </section>

      <section className="mt-8 grid gap-5 md:grid-cols-3">
        {TOOLS.map((t) => (
          <Link
            key={t.to}
            to={t.to}
            className="group rounded-2xl border border-border bg-card p-5 transition-colors hover:border-accent"
          >
            <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-accent/10 text-accent">
              <t.icon className="h-5 w-5" />
            </span>
            <h2 className="mt-4 text-base font-semibold">{t.title}</h2>
            <p className="mt-2 text-sm text-muted-foreground">{t.desc}</p>
            <span className="mt-4 inline-flex items-center text-sm font-medium text-accent">
              Open tool <ArrowRight className="ml-1.5 h-4 w-4 transition-transform group-hover:translate-x-0.5" />
            </span>
          </Link>
        ))}
      </section>

      <section className="mt-8 grid gap-5 sm:grid-cols-3">
        {[
          ["Structured output", "Every response follows a clear, professional format you can reuse."],
          ["Copy & regenerate", "One click to copy a draft or ask for a different take."],
          ["Works everywhere", "Sidebar dashboard on desktop, full-width layout on mobile."],
        ].map(([title, desc]) => (
          <div key={title} className="flex gap-3 rounded-2xl border border-border bg-surface p-4">
            <Sparkle className="mt-0.5 h-4 w-4 shrink-0 text-accent" />
            <div>
              <p className="text-sm font-medium">{title}</p>
              <p className="mt-1 text-xs text-muted-foreground">{desc}</p>
            </div>
          </div>
        ))}
      </section>

      <ResponsibleAiNotice />
    </>
  );
}
