import { ShieldAlert } from "lucide-react";

export function AiDisclaimer({ className = "" }: { className?: string }) {
  return (
    <div
      className={`flex gap-3 border border-border bg-surface p-4 text-xs leading-relaxed text-muted-foreground ${className}`}
    >
      <ShieldAlert className="h-4 w-4 flex-shrink-0 text-accent" aria-hidden="true" />
      <p>
        <span className="label-mono text-foreground">Responsible AI</span> — Output is generated by
        an AI model and can be incomplete or wrong. Review and edit everything before you send,
        share or act on it. Do not paste confidential, personal or client data into these tools, and
        keep a human accountable for every decision.
      </p>
    </div>
  );
}
